'\" t
.\"     Title: mumd
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.17
.\"      Date: 2022-10-03
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "MUMCTL" "1" "2022-10-03" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mumctl \- mumd(1) controller
.SH "SYNOPSIS"
.sp
mumctl [OPTIONS] SUBCOMMAND [ARG...]
.SH "DESCRIPTION"
.sp
mumctl is a CLI controller for mumd(1), a client daemon for Mumble, a free and
open source voice chat system.
.SH "OPTIONS"
.sp
\-h, \-\-help
.sp
.if n .RS 4
.nf
.fam C
Prints help information.
.fam
.fi
.if n .RE
.sp
\-\-version
.sp
.if n .RS 4
.nf
.fam C
Prints version information.
.fam
.fi
.if n .RE
.sp
Subcommands contain additional options.
.SH "SUBCOMMANDS"
.sp
\fBmumctl channel connect\fP NAME
.sp
.if n .RS 4
.nf
.fam C
Connect to another channel.
.fam
.fi
.if n .RE
.sp
mumctl channel list [\-s|\-\-short]
.sp
.if n .RS 4
.nf
.fam C
List all channels in the connected server.
.fam
.fi
.if n .RE
.sp
mumctl completions [bash|fish|zsh]
.sp
.if n .RS 4
.nf
.fam C
Generate a completion file for the specified shell.
.fam
.fi
.if n .RE
.sp
mumctl config KEY VALUE
.sp
.if n .RS 4
.nf
.fam C
Set a configuration value in the mumd(1) configuration file.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
See mumdrc(5) for available keys and their meaning.
.fam
.fi
.if n .RE
.sp
mumctl config\-reload
.sp
.if n .RS 4
.nf
.fam C
Force a reload of the configuration file (e.g. after editing it externally).
.fam
.fi
.if n .RE
.sp
mumctl connect HOST [\-p|\-\-port PORT] [\-\-accept\-invalid\-cert] [USERNAME] [PASSWORD]
.sp
.if n .RS 4
.nf
.fam C
Connect to a server on the specified port.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
The host may be either the name of a saved server in the configuration file
or an IP/URL, in which case a username needs to be passed as well.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If omitted, the port defaults to 64738.
.fam
.fi
.if n .RE
.sp
mumctl deafen
.sp
.if n .RS 4
.nf
.fam C
Deafen yourself.
.fam
.fi
.if n .RE
.sp
mumctl disconnect
.sp
.if n .RS 4
.nf
.fam C
Disconnect from the currently connected server.
.fam
.fi
.if n .RE
.sp
mumctl events
.sp
.if n .RS 4
.nf
.fam C
Print a list of events that have occured.
.fam
.fi
.if n .RE
.sp
mumctl help
.sp
.if n .RS 4
.nf
.fam C
Show a help message.
.fam
.fi
.if n .RE
.sp
mumctl message channel [\-r|\-\-recursive] MESSAGE [CHANNEL...]
.sp
.if n .RS 4
.nf
.fam C
Sends a message to all channels specified in the list of channels.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If \-\-recursive is set, the message is also sent to all subchannels.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If no channels are given, the message is sent to the channel we\*(Aqre currently
connected to.
.fam
.fi
.if n .RE
.sp
mumctl message user MESSAGE USER...
.sp
.if n .RS 4
.nf
.fam C
Sends a message to one or more users.
.fam
.fi
.if n .RE
.sp
mumctl messages [\-f|\-\-follow]
.sp
.if n .RS 4
.nf
.fam C
Prints all received messages since the last time this command was run.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If \-\-follow is set, wait for new messages and print them as they come
in. To exit this loop, issue a ctrl\-C.
.fam
.fi
.if n .RE
.sp
mumctl mute [USER]
.sp
.if n .RS 4
.nf
.fam C
Mute yourself or someone else.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If user is omitted, you mute yourself. Otherwise, that user is muted.
.fam
.fi
.if n .RE
.sp
mumctl server add NAME HOST [\-\-port PORT] [USERNAME] [PASSWORD]
.sp
.if n .RS 4
.nf
.fam C
Add a new saved server configuration.
.fam
.fi
.if n .RE
.sp
mumctl server config SERVER KEY VALUE
.sp
.if n .RS 4
.nf
.fam C
Configure a variable in a saved server configuration.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
See mumdrc(5) for available keys.
.fam
.fi
.if n .RE
.sp
mumctl server list
.sp
.if n .RS 4
.nf
.fam C
List all saved servers and how many are connected to them.
.fam
.fi
.if n .RE
.sp
mumctl server remove NAME
.sp
.if n .RS 4
.nf
.fam C
Remove a saved server.
.fam
.fi
.if n .RE
.sp
mumctl server rename OLD_NAME NEW_NAME
.sp
.if n .RS 4
.nf
.fam C
Rename a saved server.
.fam
.fi
.if n .RE
.sp
mumctl status
.sp
.if n .RS 4
.nf
.fam C
Show the currently connected channel and server.
.fam
.fi
.if n .RE
.sp
mumctl undeafen
.sp
.if n .RS 4
.nf
.fam C
Undeafen yourself.
.fam
.fi
.if n .RE
.sp
mumctl unmute [USER]
.sp
.if n .RS 4
.nf
.fam C
Unmute yourself or someone else.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
If user is omitted, unmute yourself. Otherwise, that user is unmuted.
.fam
.fi
.if n .RE
.sp
mumctl volume VOLUME
.sp
.if n .RS 4
.nf
.fam C
Set the volume of outgoing audio.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
1.0 is the default.
.fam
.fi
.if n .RE
.sp
mumctl volume USER VOLUME
.sp
.if n .RS 4
.nf
.fam C
Set the volume of another user\*(Aqs incoming audio.
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
1.0 is the default.
.fam
.fi
.if n .RE
.SH "AUTHORS"
.sp
Gustav Sörnäs and Eskil Queseth.
.SH "REPORTING BUGS"
.sp
Please report bugs to the Github repository at \c
.URL "https://github.com/mum\-rs/mum/" ""
or by e\-mail to \c
.MTO "gustav\(atsornas.net" "" "."
.SH "SEE ALSO"
.sp
mumd(1), mumdrc(5)